apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: porter-agent
spec:
  template:
    spec:
      containers:
        # Change the value of image field below to your controller image URL
        - image: kony168/porter-agent:v0.4.2
          name: porter-agent
